### ISSUE TITLE
Mismatch between bower.json version and resolved version

### ISSUE THREAD

**Issue by kirbywarp** [lennardv2/Leaflet.awesome-markers#28]
It seems as though there's a version mismatch with your bower.json file.  When bower tries to install Leaflet.awesome-markers as a dependency to angular-leaflet, I get the following error:

> mismatch Version declared in the json (2.0.0) is different than the resolved one (2.0.1)

Calling "bower info Leaflet.awesome-markers" tells me that version 2.0.1 should be available, and in fact the output of "bower info" shows a bower.json printout with version 2.0.1, but your current bower.json file marks the version as 2.0.0.  I don't know if its as simple as changing the version number, but I'd appreciate a fix.

**Comment by lennardv2** [comment]
I've updated the bower.json to 2.0.1, try again!

**Comment by kirbywarp** [comment]
Doesn't seem to have fixed it.

Something new I've noticed is that it is downloading an archived file rather than pulling directly from the repository.

https://github.com/lvoogdt/Leaflet.awesome-markers/archive/v2.0.1.tar.gz

Perhaps you need to update this archived file?

**Comment by lennardv2** [comment]
Allright i've updated bower.json tot 2.0.2 and created a new release (the archived file) @ 2.0.2. I think it should work now

**Comment by kirbywarp** [comment]
It didn't fix the overall process, but I'm able to install Leaflet.awesome-markers now.  Thanks!
